name: Flawless 24/7

on:
  schedule:
    - cron: '0 */5 * * *' # تشغيل احتياطي كل 5 ساعات في حال فشل الإطلاق التلقائي
  workflow_dispatch:

# ميزة تمنع تشغيل أكثر من نسخة في نفس الوقت لتجنب حظر التليجرام
concurrency:
  group: flawless-bot-24-7
  cancel-in-progress: true 

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      actions: write # ضروري جداً للسماح للسكربت بإعادة تشغيل نفسه
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
          
      - name: تثبيت المكتبات
        run: pip install -r requirements.txt
        
      - name: تشغيل السكربت (مع مؤقت زمني)
        env:
          API_ID_1: ${{ secrets.API_ID_1 }}
          API_HASH_1: ${{ secrets.API_HASH_1 }}
          SESSION_1: ${{ secrets.SESSION_1 }}
          API_ID_2: ${{ secrets.API_ID_2 }}
          API_HASH_2: ${{ secrets.API_HASH_2 }}
          SESSION_2: ${{ secrets.SESSION_2 }}
          API_ID_3: ${{ secrets.API_ID_3 }}
          API_HASH_3: ${{ secrets.API_HASH_3 }}
          SESSION_3: ${{ secrets.SESSION_3 }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          NOTIFY_USER: ${{ secrets.NOTIFY_USER }}
          VPS_CHANNEL_ID: ${{ secrets.VPS_CHANNEL_ID }}
        # أضفنا الأمر timeout ليقوم بإيقاف السكربت بعد 350 دقيقة قبل أن يتدخل GitHub
        # استخدام || true يضمن عدم فشل العملية ليسمح للخطوة التالية بالعمل
        run: timeout 350m python fatima_alzahra.py || true

      - name: إعادة التشغيل التلقائي (Loop)
        if: always() # هذه الخطوة ستعمل دائماً لتعيد تشغيل البوت
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "تم الوصول للحد الآمن، جاري إعادة تشغيل السكربت ليبدأ دورة جديدة..."
          gh workflow run "${{ github.workflow }}"


